name: MetaPy Build & Release (macOS)
on:
  push:
      branches:
          - master
jobs:
    build-mac-bigsur:
        runs-on: macos-11
        steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install Dependencies
          run: |
            source scripts/install_osx.sh
        - name: Build Wheel
          run:  |
            export LDFLAGS="-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib"
            export CPPFLAGS="-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib"
            export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
            source scripts/build_osx.sh
        - name: Uploading Python Wheels
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: PythonWheelsBigSur-${{ matrix.python-version }}
            path: dist/*.whl
    build-mac-catalina:
        runs-on: macos-10.15
        strategy:
            matrix:
                python-version: [3.10.0, 3.8.6, 3.9.6]
        steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive
        - uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install Dependencies
          run: |
            source scripts/install_osx.sh
        - name: Build Wheel
          run:  |
            export LDFLAGS="-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib"
            export CPPFLAGS="-I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib"
            export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
            source scripts/build_osx.sh
        - name: Uploading Python Wheels
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: PythonWheelsCatalina-${{ matrix.python-version }}
            path: dist/*.whl
    