name: MetaPy Build & Release (using cibuildwheel for Linux)
on:
  push:
      branches:
          - master
jobs:
    build_wheels:
      name: Build wheels on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ubuntu-20.04]
      env:
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_24
        CIBW_ARCHS_LINUX: "x86_64"
      steps:
      - uses: actions/checkout@v2
        with:
            submodules: recursive
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.0
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
    build_sdist:
      name: Build source distribution
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: Build sdist
          run: pipx run build --sdist

        - uses: actions/upload-artifact@v2
          with:
            path: dist/*.tar.gz